#!/bin/sh

# fetch rsync
if ! [ -f rsync-3.1.3.tar.gz ]; then
	ftp https://download.samba.org/pub/rsync/src/rsync-3.1.3.tar.gz
fi

# verify
_sum=$(sha256 -q rsync-3.1.3.tar.gz)

if [ "$_sum" != "55cc554efec5fdaad70de921cd5a5eeb6c29a95524c715f3bbf849235b0800c0" ]; then
	echo "verification of rsync-3.1.3.tar.gz failed" >&2
	rm rsync-3.1.3.tar.gz
	exit 1
fi

rm -rf rsync-3.1.3
tar zxf rsync-3.1.3.tar.gz || exit 1

cd rsync-3.1.3 || exit 1

./configure \
	--disable-locale \
	--disable-iconv-open \
	--disable-iconv \
	--disable-acl-support \
	--disable-xattr-support \
	--with-included-popt \
	--with-included-zlib || exit 1

# apply patches for hrsync
cp rsync.h rsync.h.orig
cp rsync.c rsync.c.orig
cp main.c main.c.orig
cp pipe.c pipe.c.orig
cp options.c options.c.orig

patch < ../patch-rsync_h	|| exit 2
patch < ../patch-rsync_c	|| exit 2
patch < ../patch-main_c	|| exit 2
patch < ../patch-pipe_c	|| exit 2
patch < ../patch-options_c	|| exit 2

make || exit 3

cd ..
cp rsync-3.1.3/rsync hrsync || exit 4
